### PR TITLE
improve the performance of Beam Search

### PR DESCRIPTION
**Pull request by xiaotaw**
Instead of `max length penalty`, it's more reasonable to use `current  length penalty` in _is_finished function.
It improved the performance in my experiment.

### CODE REVIEW

**Comment by minicheshire** [comment]
Thanks! We'll merge your PR after some experiments.

**Comment by Glaceon31** [comment]
The decoding process only finishes when all alive candidates can not outperform any finished candidate in any case (even when length is maximized and the probability of all subsequent words are 1). So we should use max length penalty here. 

Strangely, I tried to decode with your code and expect some differences in the translation. However, it yields the same translation as the origin code on a test set containing 1000+ sentences.

**Comment by xiaotaw** [comment]
my tried on several test sets, and 99.8% of the translations are the same. The differences are:
1. the ones, _using current length_,  are shorter than those _using max length_, often with one or two words.
2. a few of the translations, _using max length_, end with repeating words. it wont  when _using current length_.

In addition, _using current length_ avoids decoding <pad>s after <eos>. Decoding <pad> makes no difference to BLEU, while increases unnecessary calculation. _using current length_, in my point of view, is more reasonable.

**Comment by Glaceon31** [comment]
This PR is an algorithmic change instead of a bug fix. To make THUMT a stable and effective NMT toolkit, we only accept algorithmic change which is theoretical sound and is widely applied in the MT community or achieves stable and significant improvement on a public dataset.

Beam search is proven to be an effective decoding algorithm. Using max length sticks to the origin beam search algorithm which attempts to find a translation with **higher probability**. Using current length results in a pruning of the search space and it never finds a better translation **in terms of probability**.

Sorry that we cannot merge this for now. If there are important references (e.g. published paper) related to the superiority of using current length, please inform me.

Thanks for your contribution to THUMT!

**Comment by xiaotaw** [comment]
In <a href="https://arxiv.org/pdf/1609.08144.pdf" target="_blank">GNMT's paper</a>, lp(Y) = (5 + |Y|) ^ alpha / (5 + 1) ^ alpha, and here |Y| is the current length, not the max length, I think.

**Comment by Glaceon31** [comment]
THUMT already penalize with current length (see line 69). Max length is only used in early stopping (line 151), it is not the final loss.

**Comment by xiaotaw** [comment]
Yes, you're right. 
_loop_fn: score = log_prob / current_length_penalty (line 69~70 )
_is_finished: score = log_prob / max_length_penalty (line 151~152)


To make it clear, let's look at a concrete example. 
Assume that we have trained a MT system, and it's able to translate upper case characters into uncased ones with beam_size = 1. For example, "A B C" -> "a b c".

Given an unknown source sentence: X, the MT system has already decodes out "a b c d".
In step 5, it decodes out: ("<eos>", prob=0.5), ("e", prob=0.4). 

If using current length penalty, decoder stops here. 
If using max length penalty, decoder may continues. As a longer sentence "a b c d e f g h i ... " may  score higher due to a larger length penalty. 
 
Both of the two ways make sense, and produce good translation in practice, as we just tested them for thousands of sentences. The `max length penalty` tends to output the sentence with the highest score under the beam_size restriction, while `current length penalty` tends to produce a good enough translation at a reasonable computation cost. 

Well, it may be a practicable way that THUMT provide a option to use `current length penalty` or `max length penalty`.

**Comment by Glaceon31** [comment]
There are also examples that max length is better: when P("y_{<t} y_t y_{t+1} y_{t+2}"|x) > P("y_{<t} y_t "|x) > P("y_{<t} y_t y_{t+1}"|x), using current length will not yield the best translation "y_{<t} y_t y_{t+1} y_{t+2}".

According to our step-by-step observation into the decoding process. The NMT loss dramatically increases when useless words are decoded. We should let the model access to more translations and determine the best one.

It is true that using current length can save decoding time. However, a careful evaluation on the time cost and translation quality should be conducted before this trick can be used in practical systems.

**Comment by xiaotaw** [comment]
Here is my result on 11 data sets. Each set contains 1000+ sentences. No. 4 and No. 5 come from wmt17 (newstest2017). The exact BLEU of test sets range from 20~40. Translation was carried on GPU, and I only ran them once. But it's clear that using current lp saves a lot of time while almost does not affect BLEU.

Looking forward to your further evaluation.

test dataset | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
BLEU(current_lp)-BLEU(max_lp) | -0.04 | 0 | 0.01 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0
Time(max_lp) / second | 34 | 12 | 113 | 81 | 27 | 12 | 14 | 21 | 17 | 16 | 19
Time(current_lp) / second | 27 | 10 | 76 | 74 | 24 | 9 | 12 | 20 | 15 | 16 | 15

**Comment by Glaceon31** [comment]
We will test when we have enough resource

**Pull request closed without merging**
